travis:
  secure:
    BINSTAR_TOKEN: mJrvo71l25LTWbQ3awZ/JhEtfq86KPKpoZUXsoQqBHjSFWpSIDvlKxhbM15MUr3fxWjnHZYtTrnSGW0F3RjpyX8LYgbPsNoc/TR0ObqbN5TiYwVpx5nkS6n6VzJxX5sWstWDAAjH6QRyi+96RgCKeDn+im4v5m8au1H+xTM0LcMRDylLQRY/NtKIyfJTRRSXaibeTvvLN9HathPbkNEBlmm4U5Z4KjN/KZgzw3Jqaxl5Gd7fmqejeYSl6/YokcxquQvo2CqZGkEiYzqJs/FB9zfjHNBt7iv2qVGmBXM8HQC+uOvCqKSsCQYAQCUeICNM1S4bs0fVxGZ0BUxad+zoueEq+lL4Ta4RvzWkZSyBwWIAhIMjkB78SLLNkQaDJtd39u8w5te9l7YuO11JupNFdnEYwwr9MSTcGnp+cIoitWkZ+h+7AyDZpCplOeafh/FNL4xRP5fHvTWN4ZUeuAfiQTzwo2n29fCpgwCyWiN968Swelaotrgn04Cdp26ko4a4xazoUz1uZ7Q8LFcDRSJeXksefR1KQ2T4GzX3WYgfOOUIYK7cVVk7yWnHL4LpkiAIiDuI02LFM7f9ZDuaJjSrFntuGa/XvbR7+76xPFSkoZ9LsnR1KZxvL6UVMvl1Kpo8TWepdsmklHRKupHG+Rtp2fQkJ9r7vXPkXqvefWqTdAM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
