travis:
  secure:
    BINSTAR_TOKEN: XyUC+NIW7o+dvjsdJVRGIpyKoUhcwVDxJUGiAdeHLXnpqNDel6O0C1JWVFOPTYduKrNQ0GbKNqW6GyqDpNED5CLWCYxOwYXV+TX/5LrXbhZmRsKValWFw4t5/dyUqGFiReddWwmE+DxFUnr/nPR+FyiHxuqkkuKniD0FxIUwdy0YdYeApRFCLu7EDJJ9+YQ+aMv5VT81l1gTgNt1UqXNCzTUYQd3ME3BnAJwx0DacaPAYKBI+NbeyGG05CGmkn8r1qmP2p0YbozOo/yA8ZWJEVkWyXb7mJjSRxckHsKtjczkAF68BFd2FgyljBacEMNGPsrWe94NRZpl4M5P/Z3D6G3CDr+23wiHwuhCYeKRCTdJc8jL3g9mjWEl5icB2B4wfZkAydiESzvR3Szw5J/usjyarqQ5oiFox5Z1SzeCy6rc/WTR+f5jh7HaPN2KLcfQATz9luOcZGguSTSWxChYU6kQkJe1e3ut94ka3Q66g+fxjB2Nm3Jt/NAEY+lrkdUAQi40HTc8hNHSBXoZxPcAju03gruhfY6s7ivG35Afu/toqlSWdj22ACnwHmNh6Y5B2sTH86uxxtiwkDix11hnENCcCjb4X8/x1jJt0FjdMCVROwCx29ELSry3dABTb8E5FJ4tzOl2egc2Z1V2QXlOJjz2/zTybSL9I0OnuFxT4jw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
